### ISSUE TITLE
Selecting text and clicking on text again should release selection

### ISSUE THREAD

**Issue by lostpebble** [codex-team/editor.js#720] opened 2019-04-11 10:46 UTC
I've noticed some strange behaviour when playing with editor.js for the first time. To me it seems like very basic text editor behaviour that is not working- so its quite obvious and might be a cause of frustration for users.

* Select some text in a block
* Want to deselect that text now / or move the cursor instead to a different place inside that collection
* Single click in the selection where you want the cursor to go
* Nothing happens. The block stays selected.

I understand that you want to allow the drag functionality on the selected text (I think - currently I'm not sure as it does nothing for me). But it should be checking if the mouse was clicked and released (regular click, release the selection), or if it was clicked and not released (dragged, keep current functionality).

**Comment by gohabereg** [comment] 2019-04-11 10:48
Can't reproduce it, could you please provide some screen record?

**Comment by lostpebble** [comment] 2019-04-11 10:54
Sure:

https://www.loom.com/share/06aa19eb7ce3436eb6652912e90a62f2

**Comment by lostpebble** [comment] 2019-04-11 11:00
You know, I just tried on Firefox and the issue is not there... So I think this might be a Chrome bug.

**Comment by gohabereg** [comment] 2019-04-11 11:02
It also doesn't reproduce on example.html page and here https://codex.so/editor. Maybe it's because of iframe on the editorjs.io main page, will look at this, thanks!

**Comment by lostpebble** [comment] 2019-04-11 11:06
Yep, at https://codex.so/editor it works fine now on the same Chrome browser. It is just https://editorjs.io/ that has the issue.

**Comment by neSpecc** [comment] 2019-07-18 10:28
Fixed in 2.15 version

**Closed by neSpecc** 2019-07-18 10:28 UTC
