### ISSUE TITLE
[Bug] Unable to delete Raw HTML

### ISSUE THREAD

**Issue by carlsonorozco** [codex-team/editor.js#1652] opened 2021-04-13 15:53 UTC
Unable to delete Raw HTML

Steps to reproduce:
1. Go to editor and create a raw HTML
2. Click to tune. Toolbar icons missing

Expected behaviour: Show toolbar icons

Screenshots: 
<img width="747" alt="Screen Shot 2021-04-13 at 23 48 22" src="https://user-images.githubusercontent.com/2333279/114582452-2fcd6100-9cb3-11eb-886b-d61cc3f58673.png">

Device, Browser, OS: macOS Google Chrome 

Editor.js version: 2.20.1

Plugins you use with their versions: Raw HTML

**Comment by gohabereg** [comment] 2021-04-13 16:56
Duplicate of #1640

**Closed as completed by gohabereg** 2021-04-13 16:56 UTC
Labels: bug
