### ISSUE TITLE
[Bug] Unable to delete Code

### ISSUE THREAD

**Issue by carlsonorozco** [codex-team/editor.js#1653] opened 2021-04-13 16:19 UTC
Same behaviour of https://github.com/codex-team/editor.js/issues/1652

Steps to reproduce:
1. Go to editor and create a code
2. Click to tune. Toolbar icons missing

Expected behavior: Show toolbar icons

Device, Browser, OS: macOS Google Chrome

Editor.js version: 2.20.1

Plugins you use with their versions: Code

**Comment by gohabereg** [comment] 2021-04-13 16:56
Duplicate of #1640

**Closed as completed by gohabereg** 2021-04-13 16:56 UTC
Labels: bug
