### ISSUE TITLE
json to html on frontend...

### ISSUE THREAD

**Issue by mypetertw** [codex-team/editor.js#860] opened 2019-08-02 05:15 UTC
Json string render HTML on frontend, how can it works?

**Comment by rmlamarche** [comment] 2019-08-12 14:24
Duplicate of #676 

A read-only init option is also in the Roadmap #837 

It also depends on your needs. You can use a templating engine such as ejs or pug if you want server side rendering benefits.

Since you said "on the frontend", you can also just write a function in client side javascript that renders elements as you need, iterating over `data.blocks` with some if statements or a switch.

```javascript
function renderHTML(data) {
    let result = ``;
    for (let block of JSON.parse(data).blocks) {
      switch (block.type) {
        case 'paragraph':
          result += `<p>${block.data.text}</p>`;
          break;
        case 'header':
          result += `<h${block.data.level}>${block.data.text}</h${block.data.level}>`;
          break;
        case 'list':
          ...
      }
    }
    return result;
  }
```

**Comment by sumitvekariya** [comment] 2019-12-12 05:29
https://medium.com/@sumitvekariya7/editor-js-read-only-mode-in-angular-4f73192ed860

I have created readOnly view mode for angular using switchcase statement based on block type and I have used css classes given in editor.js iteslf, so It creates 100% same user interface.

**Comment by docluv** [comment] 2020-03-28 21:23
This seems like the best approach. Seems like you will need a rendering class for each custom block.

**Comment by pavittarx** [comment] 2020-04-29 07:39
If you want an extendable framework-free approach:  https://github.com/pavittarx/editorjs-html. Use it in the browser, or node, extend it to suit your needs.  
I created to use it with my own project, but would like to see if anyone else would want to use it.
* ~1kb bundles, ~200 downloads in just two days.  
* No switch cases or if-else conditions.

**Comment by MichaelMikeJones** [comment] 2020-10-11 10:58
I've created a package for this purpose. editorjs-parser
It supports :

    Paragraph
    Header
    Table
    Raw
    Delimiter
    Code
    Quote
    List
    Embed
    Image

It also is configurable.

**Comment by khaydarov** [comment] 2020-11-21 17:13
read-only mode is release with [v2.19](https://github.com/codex-team/editor.js/releases/tag/v2.19.0)

**Closed by khaydarov** 2020-11-21 17:13 UTC
