### ISSUE TITLE
Can not find a Block from this child Node

### ISSUE THREAD

**Issue by aromero86** [codex-team/editor.js#761] opened 2019-05-08 11:11 UTC
Hi guys, sometimes I get this error:

```
core.js:14597 ERROR Error: Can not find a Block from this child Node
    at e.value (editor.js:12)
    at e.value (editor.js:22)
    at HTMLDocument.<anonymous> (editor.js:22)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:16147)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:498)
    at invokeTask (zone.js:1744)
    at HTMLDocument.globalZoneAwareCaptureCallback (zone.js:1802)
```

I don't understand how avoid it. 

Thank you

**Comment by aromero86** [comment] 2019-05-08 21:15
Hi again guys, I change something in my code and error disappeared. Sorry for the lack of information :(

**Comment by tanepiper** [comment] 2019-06-05 08:32
Looks like the bug is resolved in this PR?

I do get this error on https://tinynodes-ngx.firebaseapp.com/ngx-editorjs-demo/angular-form

I can reproduce it by clearing a form and then calling save, if the editor was not focused it throws this. Focus the editor and it fixes the issue. 

Could this be fixed for the next release @khaydarov @neSpecc?

**Comment by neSpecc** [comment] 2019-06-05 10:23
@tanepiper yes, release is coming in next few days.

**Closed** 2019-06-12 17:39 UTC
Labels: bug
