### ISSUE TITLE
Backspace Deleting Whole Block

### ISSUE THREAD

**Issue by CITGuru** [codex-team/editor.js#810] opened 2019-06-22 21:17 UTC
Backspace is deleting the whole block. I notice while typing with it. Whenever I pressed backspace it deletes the whole block

**Comment by khaydarov** [comment] 2019-06-24 17:03
@CITGuru Hi! Will be fixed in the next release

**Comment by blockchain-expert** [comment] 2019-12-13 11:47
Is there any solution for this? I have this issue.

**Comment by neSpecc** [comment] 2019-12-13 14:07
@blockchain-expert @CITGuru we need more details: detailed steps to reproduce, editor.js version you use.

**Comment by md-haroon** [comment] 2020-06-16 05:55
HI 

> Backspace is deleting the whole block. I notice while typing with it. Whenever I pressed backspace it deletes the whole block

@CITGuru  how to solve this problem ,, i'm also facing the same problem

**Comment by neSpecc** [comment] 2020-09-01 18:01
Still no steps to reproduce. If someone will face that, please provide steps or a reproducible demo page. In that case, we will reopen this issue.

**Closed by neSpecc** 2020-09-01 18:01 UTC

**Comment by terryureche** [comment] 2020-09-28 09:37
Hi,

I have the same issue.

Browser: Chrome.Version 85.0.4183.121 (Official Build) (64-bit)
Operating system: Mac OS Catalina 10.15.6 / Windows 10 64-bit

Steps to reproduce the issue:

1.Install Sapling plugin for Chrome
2.Any blocks will be cut when the backspace is pressed.

There seems to be a conflict with Sapling plugin for chrome extensions.

**Comment by neerajhbhat** [comment] 2021-11-22 17:12
Hi, Any update on this?
