### ISSUE TITLE
Not working Delete button with blocks

### ISSUE THREAD

**Issue by Flashantik** [codex-team/editor.js#2464] opened 2023-09-01 09:55 UTC
When selecting multiple paragraphs and pressing the delete key, nothing happens, the backspace key works as expected.

Steps to reproduce:
1. Open editorjs
2. create block with text
3. select block or blocks
4. press delete button on keyboard

Expected behavior:
blocks would be removed

Screenshots:

https://github.com/codex-team/editor.js/assets/25429994/08defd5b-ac8a-48ed-b449-28238f8a873f

Device, Browser, OS:
MacOS, Chrome

Editor.js version: last 

Plugins you use with their versions: none

**Comment by lijie1129** [comment] 2023-09-12 16:38
Hi, @Flashantik 

I can't reproduce this issue. Has this issue been fixed?

https://github.com/codex-team/editor.js/assets/5371749/fd44e784-62f6-48f8-b3d4-42fcce451141

**Comment by Flashantik** [comment] 2023-09-19 11:36
> Hi, @Flashantik
> 
> I can't reproduce this issue. Has this issue been fixed?
> 
>  reproduce.mp4

You are press backspace, "backspace" button works fine! But not working "delete" button. In Mac fn + backspace. 
Check out my video, there's a delete button. 
<img width="157" alt="Screenshot 2023-09-19 at 13 32 53" src="https://github.com/codex-team/editor.js/assets/25429994/421214b8-f2ca-4b6e-ae83-900c5fd52598">
There is a backspace 
<img width="64" alt="Screenshot 2023-09-19 at 13 36 04" src="https://github.com/codex-team/editor.js/assets/25429994/1c445ad6-dbf8-44a7-9532-09c9d21dca07">

**Comment by neSpecc** [comment] 2023-09-19 12:12
@Flashantik What Editor.js version do you use?

**Comment by lijie1129** [comment] 2023-09-26 07:16
> > Hi, @Flashantik
> > I can't reproduce this issue. Has this issue been fixed?
> > reproduce.mp4
> 
> You are press backspace, "backspace" button works fine! But not working "delete" button. In Mac fn + backspace. Check out my video, there's a delete button. <img alt="Screenshot 2023-09-19 at 13 32 53" width="157" src="https://user-images.githubusercontent.com/25429994/268939431-421214b8-f2ca-4b6e-ae83-900c5fd52598.png"> There is a backspace <img alt="Screenshot 2023-09-19 at 13 36 04" width="64" src="https://user-images.githubusercontent.com/25429994/268939951-1c445ad6-dbf8-44a7-9532-09c9d21dca07.png">

Hi, @Flashantik 

Thanks for your reminder.

This problem cannot be reproduced in version `2.29.0-rc.1`, but it can be reproduced in https://editorjs.io/ (it is currently using version `2.26.5`), so this problem has been fixed in version `2.29.0-rc.1`.

<img width="1611" alt="image" src="https://github.com/codex-team/editor.js/assets/5371749/f560bb23-7e66-41b5-8127-e2a7a94efed3">

**Comment by Flashantik** [comment] 2023-09-26 14:30
> > > Hi, @Flashantik
> > > I can't reproduce this issue. Has this issue been fixed?
> > > reproduce.mp4
> > 
> > 
> > You are press backspace, "backspace" button works fine! But not working "delete" button. In Mac fn + backspace. Check out my video, there's a delete button. <img alt="Screenshot 2023-09-19 at 13 32 53" width="157" src="https://user-images.githubusercontent.com/25429994/268939431-421214b8-f2ca-4b6e-ae83-900c5fd52598.png"> There is a backspace <img alt="Screenshot 2023-09-19 at 13 36 04" width="64" src="https://user-images.githubusercontent.com/25429994/268939951-1c445ad6-dbf8-44a7-9532-09c9d21dca07.png">
> 
> Hi, @Flashantik
> 
> Thanks for your reminder.
> 
> This problem cannot be reproduced in version `2.29.0-rc.1`, but it can be reproduced in https://editorjs.io/ (it is currently using version `2.26.5`), so this problem has been fixed in version `2.29.0-rc.1`.
> 
> <img alt="image" width="1611" src="https://user-images.githubusercontent.com/5371749/270569515-f560bb23-7e66-41b5-8127-e2a7a94efed3.png">

Yeah in 2.29.0-rc.1 always is ok. I'll wait for the release

**Closed as completed** 2024-10-09 08:15 UTC
Labels: bug
