### ISSUE TITLE
[Bug] Settings Toolbar content rendering

### ISSUE THREAD

**Issue by blnttg** [codex-team/editor.js#1307] opened 2020-09-10 15:01 UTC
After clicking the Settings Button (without any actual modifications to the content) repeatedly, the Settings Toolbar content rendering multiple times. You can try this on the offical website, I could reproduce it there too.

Screenshots:
![image (1)](https://user-images.githubusercontent.com/5064256/92748282-81f08180-f374-11ea-8fdd-338de3c9b75e.png)

Device, Browser, OS: 
Windows 10 Pro 1909, Firefox 80.0.1 (tried it with the latest Chrome too, but it was working as intended there)

Editor.js version: 2.18.0

Plugins you use with their versions: all official plugins.

**Comment by robonetphy** [comment] 2020-10-05 17:47
Hi @blnttg,
We have already included this feature in our next version.
duplicate of #1273

**Closed** 2020-10-05 17:50 UTC
Labels: bug
