### ISSUE TITLE
onChange doesn't trigger on changing existing blocks on 2.25.0

### ISSUE THREAD

**Issue by HenglyEver** [codex-team/editor.js#2155] opened 2022-10-27 20:31 UTC
I just upgraded to `2.25.0` and found out that `onChange` callback doesn't trigger on changing existing blocks. For example, I have an existing text block, and changing its content doesn't trigger `onChange` but if I add a new block, it works fine.

My configuration
```
new EditorJS({
..., // other configs
onChange: () => {
    debugger;
    this.editor.save().then(data => {
      // Save code block
    });
  },
});
```

**Comment by xenobytezero** [comment] 2022-11-07 03:12
Having the same issue, the onChange seems very inconsistantly called.

Looks like it has something to do with the debounce function wrapped around `didMutated` in `src\components\block\index.ts`. 

I built a version of the library without that debounce and onChange is called every single time without fail.

**Comment by Y-k-Y** [comment] 2022-11-09 00:02
Can you provide reproducible code @HenglyEver? I just tried 2.25 from cdn and it seems it works well to me.

**Comment by xenobytezero** [comment] 2022-11-09 01:09
So starting up my dev environment today I can no longer see the issue, and I have no idea whats changed. If it happens again I'll repost.

**Comment by HenglyEver** [comment] 2022-11-09 12:20
@xenobytezero Yes, exactly, I have the same situation. It just works fine now and I didn't change anything.
@Y-k-Y I will provide one when it happens again, for now, it seems to work fine :/

**Comment by xenobytezero** [comment] 2022-11-09 12:23
Transitive dependency updated in the background? Got no idea.

**Comment by Y-k-Y** [comment] 2022-11-09 14:18
I'll close this issue since the problem is gone? Reopen issue any time if it happen again

**Closed as completed by Y-k-Y** 2022-11-09 14:18 UTC
Labels: bug
