### ISSUE TITLE
Image caption input display incorrect

### ISSUE THREAD

**Issue by ndlinh-celtic** [codex-team/editor.js#876] opened 2019-08-29 10:48 UTC
Browser: Firefox 68.0.2 (64-bit)
OS: MacOS

![Screen Shot 2019-08-29 at 5 10 34 PM](https://user-images.githubusercontent.com/8649918/63934260-1d25fa00-ca85-11e9-834c-1b85aa2c59d0.png)

**Comment by mupkoo** [comment] 2019-10-22 09:28
Looks like the problem is coming from the fact that initially the node is empty that's why it is collapsed (0 height, just padding). It might be a problem with Firefox and contenteditable as even adding a `min-height` it does not solve the cursor.

<img width="536" alt="Screen Shot 2019-10-22 at 12 28 30" src="https://user-images.githubusercontent.com/1788571/67273613-7cbde600-f4c7-11e9-99e6-df6058dd5481.png">

**Comment by mupkoo** [comment] 2019-10-23 21:43
Once you enter something and delete it, it works as expected. Looks like it is because of the add `<br>` tag.

**Comment by neSpecc** [comment] 2019-12-07 16:12
Resolved in 2.16.1

**Closed by neSpecc** 2019-12-07 16:12 UTC
