### ISSUE TITLE
When opening the toolbar, the save method is called. Why?

### ISSUE THREAD

**Issue by mak33v** [codex-team/editor.js#2783] opened 2024-07-17 17:20 UTC
When opening the toolbar, the save method is called. Why?

**Comment by neSpecc** [comment] 2024-07-17 17:30
It is used for Conversion Toolbar. 

When a tool has several toolbox entries, we need to make sure we do not add a toolbox item with the same data to the resulting array. This helps exclude duplicates. For example, for Heading 2 it will show Heading 1 and Heading 3 in a conversion menu.

I'll close this issue since it is not a bug. If you have any problems with it, please, explain them.

**Closed as completed by neSpecc** 2024-07-17 17:30 UTC

**Comment by mak33v** [comment] 2024-07-17 17:54
> It is used for Conversion Toolbar.
> 
> When a tool has several toolbox entries, we need to make sure we do not add a toolbox item with the same data to the resulting array. This helps exclude duplicates. For example, for Heading 2 it will show Heading 1 and Heading 3 in a conversion menu.
> 
> I'll close this issue since it is not a bug. If you have any problems with it, please, explain them.

Thank you for such a quick response.

I use the save method for numerous logic, including saving data to the database, and I would not like it to be executed every time the block menu is opened, in my opinion, calling the save method when opening the block menu looks generally illogical, how can I avoid this ?

The first thing that came to my mind was to add an open menu flag and, depending on its value, execute the saving logic or not, but I could not find any hooks responsible for opening and closing the menu.

**Comment by neSpecc** [comment] 2024-07-18 00:43
> I use the save method for numerous logic

Are you talking about the save() method of a particular tool? If so, it is not the best place to save data to the database.

Or save() of a whole editor? If so, we don't call it, probably you do.
