### ISSUE TITLE
console show 'Editor.js saving' log is too much times and poor peformance when paste more than one hundred lines❓

### ISSUE THREAD

**Issue by liruixue** [codex-team/editor.js#2161] opened 2022-11-07 11:06 UTC
**Question**

console show 'Editor.js saving' log is too much times and poor peformance when paste more than one hundred

**Context**
Version: editorjs-2.25.0

After I copy more than one handred lines sentences from notepad++, I pasted them on editorjs(The words is around two thousand)， but I have to wait ten second, and I found the consolw will print many 'Editor.js saving' log， how can I disable those logs and improve the paste performance.

**Related issues**
None

**Comments**

Is this a performance issue or any configuration can disable those  'Editor.js saving' log print? Look forward your reply, thanks.

**Comment by neSpecc** [comment] 2022-11-07 11:15
We'll check it, thanks

**Comment by liruixue** [comment] 2022-11-07 12:50
> We'll check it, thanks

Thanks for your quick reply, and I also checked that this problem is not exist at version 2.23.1, seem that the issue was introduced from 2.24.0

**Comment by PatrykDubinski** [comment] 2022-11-29 07:27
Any news here? I'm having the same issue when I have ~60 blocks and Editor.js saving is logging a lot when scrolling through the document.

**Comment by Y-k-Y** [comment] 2023-02-16 16:53
@liruixue @PatrykDubinski I know it's too late but can you guys provide reproducible sample?? I was trying to reproduce the bug but couldn't make it

**Comment by neSpecc** [comment] 2023-02-20 15:48
I'm not sure I've got the problem correctly.

We have an `Editor.js saving` log that work through the `groupCollapsed` method. It looks fine (collapsed) on small amount of blocks.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/3684889/220150082-c6dd5fc6-0aae-4a82-9e4a-7566935705a5.png">

But if we have many blocks, `groupCollapsed` stopped collapsing and displays in uncollapsed state.

<img width="926" alt="image" src="https://user-images.githubusercontent.com/3684889/220150412-b7975fe0-c264-43f3-8b15-a56b4518f747.png">

Probably, that is because browser filters some logs (beginning of groupCollapsed) due some reason.

Is it the problem you're describing?

**Comment by Y-k-Y** [comment] 2023-03-09 15:59
@neSpecc I remember that the bug what @liruixue is talking about happened even on example.html and the low performance when pasting 100+ lines as well but it's not happening since nowhere. I've tried to reproduce this bug on several versions but none of them can produce the bug.
Maybe we can close this issue for now and reopen it when the bug reappear?

**Comment by neSpecc** [comment] 2023-03-09 16:01
@Y-k-Y sounds reasonable. I'm closing it until some details will be provided

**Closed as completed by neSpecc** 2023-03-09 16:01 UTC
